//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaretUyg_CodeFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public string AdminAd { get; set; }
        public int AdminSifre { get; set; }
        public string TxtSifre { get; internal set; }
    }
}
