//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaretUyg_CodeFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbETicaretEntities : DbContext
    {
        public DbETicaretEntities()
            : base("name=DbETicaretEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategorilers> Kategorilers { get; set; }
        public virtual DbSet<Musterilers> Musterilers { get; set; }
        public virtual DbSet<Siparislers> Siparislers { get; set; }
        public virtual DbSet<Urunlers> Urunlers { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
    }
}
