//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaretUyg_CodeFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparislers
    {
        public int SiparisId { get; set; }
        public System.DateTime SiparisTarih { get; set; }
        public decimal SiparisToplamFiyat { get; set; }
        public Nullable<int> Urunler_UrunId { get; set; }
        public int MusteriId { get; set; }
    
        public virtual Musterilers Musterilers { get; set; }
        public virtual Urunlers Urunlers { get; set; }
        public virtual Urunlers Urunlers1 { get; set; }
    }
}
